name: Run Pytests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14'] # important to quote '3.10' to avoid YAML parsing it as a float

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e . pytest pytest-cov pytest-xdist

      - name: Run tests
        run: |
          pytest tests/pytest/ --bigchange-policy=warn \
                --cov=DARTassembler --cov-report=xml --cov-report=term-missing

      - name: Upload to Codecov
        if: matrix.os == 'macos-latest' && matrix.python-version == '3.12'
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true